import { Geist, Geist_Mono, Exo, Kanit, Comfortaa, Audiowide, Pacifico, Playfair_Display, Cormorant, PT_Serif } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header/header-wrapper";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo = Exo({
    variable: "--font-exo",
    subsets: ["latin"],
    weight: ["100", "400", "700", "900"], // Use only the weights you need
  });
  
  const kanit = Kanit({
    variable: "--font-kanit",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Add all the Kanit weights
    style: ["normal", "italic"], // Include both normal and italic styles
  });

  const comfortaa = Comfortaa({
    variable: "--font-comfortaa", // Custom CSS variable
    subsets: ["latin"], // Ensure Latin characters are loaded
    weight: ["300", "400", "500", "600", "700"], // Load specific font weights
  });

const audiowide = Audiowide({
  variable: "--font-audiowide", // Define a CSS variable for the font
  subsets: ["latin"], // Ensure Latin characters are loaded
  weight: "400", // Audiowide only has weight 400
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  weight: '400',
  subsets: ['latin'],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "700", "900"], // Choose the weights you need
  style: ["normal", "italic"],  // Include normal and italic styles
});

const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Adjust weights as needed
  style: ["normal", "italic"], // Include italic if required
});

const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  subsets: ["latin"],
  weight: ["400", "700"], // Add other weights if needed
  style: ["normal", "italic"], // Include italic if required
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
    <ClerkProvider
        appearance={{
            baseTheme: dark,
        }}
    >
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${exo.variable} ${kanit.variable} ${comfortaa.variable} ${audiowide.variable} ${pacifico.variable} ${playfair.variable} ${cormorant.variable} ${ptSerif.variable}`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />
                    <main className="w-full min-h-screen">
                        {children}
                    </main>
                    <Toaster richColors />

                    <footer className="w-full text-center text-[0.7rem] py-2 bg-muted/50 text-[#777777] font-kanit">
                        made by ARIJIT
                    </footer>

                </ThemeProvider>
            </body>
        </html>
    </ClerkProvider>
    );
}
